### ISSUE TITLE
error: Decryption Failure: Could not auto-detect algorithm used for encryption

### ISSUE THREAD

**Issue by TobseF** [BaderEddineOuaich/Enigma#6]
The decrypt action in Enigma fails with the message 
> _Could not auto-detect algorithm used for encryption_
<img width="481" alt="2022-10-12_22h23_24" src="https://user-images.githubusercontent.com/1190109/195440520-54bef079-5b36-4590-9b7a-1cd36d322d6c.png">

Version: `2.1.0`
OS: `Windows 10 x64 DE`

### Settings
Algorith: `Twofish`
Cipher: `N1ayjeHpeFQvRSmTnj87WaX71XptTKgJfGRj0ZiKkdc=`
Password: `123`

I created the cypher with the tool on:
https://www.tools4noobs.com/online_tools/encrypt/
Password: `123`
Input: `My secret for Enigma`
Mode: `CBC`
Output Encoding: `Base64`
Algorithm: `Twofish`
Result: `N1ayjeHpeFQvRSmTnj87WaX71XptTKgJfGRj0ZiKkdc=`

**Comment by baderouaich** [comment]
Hello @TobseF, the reason decryption fails because of the following reasons:
- The website encryption does not use authenticated encryption GCM. by default, Enigma uses GCM authentication with TwoFish since its highly secure than CBC.
- Enigma has its own way of encrypting buffers, when a text is encrypted, 3 parts are concatenated to the output (algorithm type (so we can detect back which algo was used for encryption) + IV (aka salt) + cipher), the website does not output encryptions this way, only buffers encrypted with this program can be decrypted back with it.

I hope this clarifies the issue.
